"""Subcategory taxonomy translations, keyed by canonical English label.

Companion to ``labels.py`` (see its module note). ``SUBCATEGORY_LABELS[lang][en]``
gives the display label; a missing lang/key falls back to the English label.
Internationally-recognised Japanese loanwords (Ramen, Sushi, Izakaya, Sauna, …) are
kept transliterated per script rather than force-translated.

NOTE: machine-authored translations — have a native speaker review before production.
"""
from __future__ import annotations

SUBCATEGORY_LABELS: dict[str, dict[str, str]] = {
    "ko": {
        "Standing Bar": "서서 마시는 술집",
        "Whisky & Cocktail Bar": "위스키·칵테일 바",
        "Izakaya": "이자카야",
        "Craft Beer & Beer Bar": "수제 맥주·비어 바",
        "Wine Bar": "와인 바",
        "Sake Bar": "사케 바",
        "Sports Bar": "스포츠 바",
        "Free-Time & Late-Night Pack": "프리타임·심야 패키지",
        "Solo Karaoke": "혼자 노래방",
        "Collab & Anime Room": "콜라보·애니메이션 룸",
        "Standard Karaoke Box": "일반 노래방",
        "Party Room": "파티룸",
        "Tickets & Services": "티켓·각종 서비스",
        "Sweets & Ice Cream": "디저트·아이스크림",
        "Drinks & Alcohol": "음료·주류",
        "Daily Goods & Sundries": "생활용품·잡화",
        "Bento & Onigiri": "도시락·삼각김밥",
        "Used & Retro Games": "중고·레트로 게임",
        "CDs & Records": "CD·레코드",
        "Trading Cards": "트레이딩 카드",
        "Musical Instruments": "악기",
        "Figures & Hobby": "피규어·취미",
        "Anime & Character Goods": "애니메이션·캐릭터 굿즈",
        "Compact Car": "소형차",
        "Luxury & Sports Car": "고급차·스포츠카",
        "Minivan (Large Group)": "미니밴(다인승)",
        "Car Sharing": "카셰어링",
        "Electric Vehicle": "전기차",
        "Standard Car": "일반 승용차",
        "Vintage & Secondhand": "빈티지·중고 의류",
        "Kimono & Traditional Wear": "기모노·전통 의상",
        "Fast Fashion": "패스트 패션",
        "Streetwear": "스트리트 패션",
        "Shoes & Sneakers": "신발·스니커즈",
        "Sportswear": "스포츠웨어",
        "Select Shop": "셀렉트 숍",
        "Cakes & Pastries": "케이크·양과자",
        "Crepes & Pancakes": "크레페·팬케이크",
        "Taiyaki & Dorayaki": "타이야키·도라야키",
        "Soft Serve & Ice Cream": "소프트아이스크림·아이스크림",
        "Chocolate Specialist": "초콜릿 전문점",
        "Wagashi (Japanese Sweets)": "화과자(일본 전통 과자)",
        "Bubble Tea & Drink Stand": "버블티·음료 스탠드",
        "Theme Cafe (Anime & Animals)": "테마 카페(애니메이션·동물)",
        "Chain Cafe": "체인 카페",
        "House-Roasted Coffee": "자가 로스팅 커피",
        "Retro Kissaten": "레트로 킷사텐",
        "Kimono Dressing & Hair Styling": "기모노 착장·헤어 세팅",
        "Cut & Color": "커트·염색",
        "Head Spa": "헤드 스파",
        "Nail Salon": "네일 살롱",
        "Eyelash Extensions": "속눈썹 연장",
        "Okonomiyaki & Monjayaki": "오코노미야키·몬자야키",
        "Soba & Udon": "소바·우동",
        "Tempura & Tonkatsu": "튀김·돈카츠",
        "Indian Cuisine": "인도 요리",
        "Chinese Cuisine": "중화 요리",
        "Yakiniku & Horumon": "야키니쿠·곱창",
        "Korean Cuisine": "한국 요리",
        "Ramen": "라멘",
        "Italian Cuisine": "이탈리아 요리",
        "Sushi & Seafood": "스시·해산물",
        "100-Yen Shop": "100엔 숍",
        "Outlet": "아울렛",
        "Household Goods": "생활 잡화",
        "General Discount": "종합 할인점",
        "Duty-Free Store": "면세 전문점",
        "Anma & Shiatsu": "안마·지압",
        "Reflexology (Foot Massage)": "리플렉솔로지(발 마사지)",
        "Quick Massage": "퀵 마사지",
        "Dry Head Spa": "드라이 헤드 스파",
        "Thai Massage": "타이 마사지",
        "Seitai & Chiropractic": "정체·카이로프랙틱",
        "Oversized Luggage": "대형·특대 수하물",
        "Staffed Luggage Counter": "유인 수하물 보관 카운터",
        "Same-Day Hotel Delivery": "숙소 당일 배송",
        "Coin Lockers": "코인 로커",
        "Airport Delivery": "공항 배송",
        "Fitness Gym": "피트니스 짐",
        "Bouldering": "볼더링",
        "24-Hour Gym": "24시간 짐",
        "Yoga & Pilates": "요가·필라테스",
        "Pool & Swimming": "수영장·스위밍",
        "Golf Range": "골프 연습장",
        "Large Bookstore": "대형 서점",
        "Art & Photography Books": "예술·사진집",
        "Foreign & Multilingual Books": "외국서적·다언어 서적",
        "Manga & Comics": "만화·코믹",
        "Antiquarian Books": "헌책방",
        "Supplements & Health Foods": "보충제·건강식품",
        "Medicine & Remedies": "의약품·상비약",
        "Cosmetics & Skincare": "화장품·스킨케어",
        "Hair & Body Care": "헤어케어·보디케어",
        "Baby Products": "유아용품",
        "Gyudon (Beef Bowl)": "규동(소고기덮밥)",
        "Curry": "카레",
        "Fried Chicken": "프라이드 치킨",
        "Hamburgers": "햄버거",
        "Sandwiches & Bakery": "샌드위치·베이커리",
        "Standing Soba": "서서 먹는 소바",
        "Super Sento Bathhouse": "슈퍼 목욕탕(센토)",
        "Natural Hot Spring": "천연 온천",
        "Sauna": "사우나",
        "Private Bath": "개별실·전세탕",
        "Esthetic Spa": "에스테틱",
        "Ganbanyoku (Stone Sauna)": "암반욕",
        "Game Consoles & Software": "게임기·소프트웨어",
        "Audio & Earphones": "오디오·이어폰",
        "PC & Phone Accessories": "PC·스마트폰 주변기기",
        "Beauty Appliances": "미용 가전",
        "Cameras & Lenses": "카메라·렌즈",
        "Kitchen Appliances": "조리 가전",
        "Multiplex Cinema": "멀티플렉스 영화관",
        "Anime Screenings": "애니메이션 상영",
        "Art-House Cinema": "미니시어터·독립영화관",
        "IMAX & 4DX": "IMAX·4DX",
    },
    "zh-Hans": {
        "Standing Bar": "站着喝酒吧",
        "Whisky & Cocktail Bar": "威士忌·鸡尾酒吧",
        "Izakaya": "居酒屋",
        "Craft Beer & Beer Bar": "精酿啤酒·啤酒吧",
        "Wine Bar": "葡萄酒吧",
        "Sake Bar": "清酒吧",
        "Sports Bar": "体育酒吧",
        "Free-Time & Late-Night Pack": "自由时间·深夜套餐",
        "Solo Karaoke": "一人卡拉OK",
        "Collab & Anime Room": "联名·动漫主题房",
        "Standard Karaoke Box": "普通卡拉OK包厢",
        "Party Room": "派对房",
        "Tickets & Services": "票务·各类服务",
        "Sweets & Ice Cream": "甜点·冰淇淋",
        "Drinks & Alcohol": "饮料·酒类",
        "Daily Goods & Sundries": "日用品·杂货",
        "Bento & Onigiri": "便当·饭团",
        "Used & Retro Games": "二手·复古游戏",
        "CDs & Records": "CD·唱片",
        "Trading Cards": "集换式卡牌",
        "Musical Instruments": "乐器",
        "Figures & Hobby": "手办·模型",
        "Anime & Character Goods": "动漫·角色周边",
        "Compact Car": "紧凑型车",
        "Luxury & Sports Car": "豪华车·跑车",
        "Minivan (Large Group)": "商务车(多人)",
        "Car Sharing": "汽车共享",
        "Electric Vehicle": "电动车",
        "Standard Car": "普通轿车",
        "Vintage & Secondhand": "古着·二手服饰",
        "Kimono & Traditional Wear": "和服·传统服饰",
        "Fast Fashion": "快时尚",
        "Streetwear": "街头潮流",
        "Shoes & Sneakers": "鞋·运动鞋",
        "Sportswear": "运动服",
        "Select Shop": "精选集合店",
        "Cakes & Pastries": "蛋糕·西点",
        "Crepes & Pancakes": "可丽饼·松饼",
        "Taiyaki & Dorayaki": "鲷鱼烧·铜锣烧",
        "Soft Serve & Ice Cream": "软冰淇淋·冰淇淋",
        "Chocolate Specialist": "巧克力专门店",
        "Wagashi (Japanese Sweets)": "和果子(日式点心)",
        "Bubble Tea & Drink Stand": "珍珠奶茶·饮品店",
        "Theme Cafe (Anime & Animals)": "主题咖啡馆(动漫·动物)",
        "Chain Cafe": "连锁咖啡馆",
        "House-Roasted Coffee": "自家烘焙咖啡",
        "Retro Kissaten": "复古喫茶店",
        "Kimono Dressing & Hair Styling": "和服着装·发型设计",
        "Cut & Color": "剪发·染发",
        "Head Spa": "头部护理",
        "Nail Salon": "美甲沙龙",
        "Eyelash Extensions": "睫毛嫁接",
        "Okonomiyaki & Monjayaki": "大阪烧·文字烧",
        "Soba & Udon": "荞麦面·乌冬面",
        "Tempura & Tonkatsu": "天妇罗·炸猪排",
        "Indian Cuisine": "印度料理",
        "Chinese Cuisine": "中华料理",
        "Yakiniku & Horumon": "烤肉·内脏烧",
        "Korean Cuisine": "韩国料理",
        "Ramen": "拉面",
        "Italian Cuisine": "意大利料理",
        "Sushi & Seafood": "寿司·海鲜",
        "100-Yen Shop": "百元店",
        "Outlet": "奥特莱斯",
        "Household Goods": "生活杂货",
        "General Discount": "综合折扣店",
        "Duty-Free Store": "免税专门店",
        "Anma & Shiatsu": "按摩·指压",
        "Reflexology (Foot Massage)": "足底按摩",
        "Quick Massage": "快速按摩",
        "Dry Head Spa": "干式头疗",
        "Thai Massage": "泰式按摩",
        "Seitai & Chiropractic": "整体·脊椎矫正",
        "Oversized Luggage": "大型·超大行李",
        "Staffed Luggage Counter": "人工寄存柜台",
        "Same-Day Hotel Delivery": "当日送达酒店",
        "Coin Lockers": "投币储物柜",
        "Airport Delivery": "机场配送",
        "Fitness Gym": "健身房",
        "Bouldering": "抱石攀岩",
        "24-Hour Gym": "24小时健身房",
        "Yoga & Pilates": "瑜伽·普拉提",
        "Pool & Swimming": "泳池·游泳",
        "Golf Range": "高尔夫练习场",
        "Large Bookstore": "大型书店",
        "Art & Photography Books": "艺术·摄影集",
        "Foreign & Multilingual Books": "外文·多语种书籍",
        "Manga & Comics": "漫画",
        "Antiquarian Books": "旧书店",
        "Supplements & Health Foods": "保健品·健康食品",
        "Medicine & Remedies": "药品·常备药",
        "Cosmetics & Skincare": "化妆品·护肤",
        "Hair & Body Care": "护发·身体护理",
        "Baby Products": "婴儿用品",
        "Gyudon (Beef Bowl)": "牛肉盖饭",
        "Curry": "咖喱",
        "Fried Chicken": "炸鸡",
        "Hamburgers": "汉堡",
        "Sandwiches & Bakery": "三明治·烘焙",
        "Standing Soba": "站着吃荞麦面",
        "Super Sento Bathhouse": "超级钱汤",
        "Natural Hot Spring": "天然温泉",
        "Sauna": "桑拿",
        "Private Bath": "包间·包场浴池",
        "Esthetic Spa": "美容护理",
        "Ganbanyoku (Stone Sauna)": "岩盘浴",
        "Game Consoles & Software": "游戏机·软件",
        "Audio & Earphones": "音响·耳机",
        "PC & Phone Accessories": "电脑·手机周边",
        "Beauty Appliances": "美容家电",
        "Cameras & Lenses": "相机·镜头",
        "Kitchen Appliances": "厨房家电",
        "Multiplex Cinema": "多厅影院",
        "Anime Screenings": "动画电影放映",
        "Art-House Cinema": "艺术影院·独立影院",
        "IMAX & 4DX": "IMAX·4DX",
    },
    "zh-Hant": {
        "Standing Bar": "站著喝酒吧",
        "Whisky & Cocktail Bar": "威士忌·雞尾酒吧",
        "Izakaya": "居酒屋",
        "Craft Beer & Beer Bar": "精釀啤酒·啤酒吧",
        "Wine Bar": "葡萄酒吧",
        "Sake Bar": "清酒吧",
        "Sports Bar": "運動酒吧",
        "Free-Time & Late-Night Pack": "自由時間·深夜套餐",
        "Solo Karaoke": "一人卡拉OK",
        "Collab & Anime Room": "聯名·動漫主題房",
        "Standard Karaoke Box": "一般卡拉OK包廂",
        "Party Room": "派對房",
        "Tickets & Services": "票務·各類服務",
        "Sweets & Ice Cream": "甜點·冰淇淋",
        "Drinks & Alcohol": "飲料·酒類",
        "Daily Goods & Sundries": "日用品·雜貨",
        "Bento & Onigiri": "便當·飯糰",
        "Used & Retro Games": "二手·復古遊戲",
        "CDs & Records": "CD·黑膠唱片",
        "Trading Cards": "集換式卡牌",
        "Musical Instruments": "樂器",
        "Figures & Hobby": "公仔·模型",
        "Anime & Character Goods": "動漫·角色周邊",
        "Compact Car": "小型車",
        "Luxury & Sports Car": "豪華車·跑車",
        "Minivan (Large Group)": "商務車(多人)",
        "Car Sharing": "汽車共享",
        "Electric Vehicle": "電動車",
        "Standard Car": "一般轎車",
        "Vintage & Secondhand": "古著·二手服飾",
        "Kimono & Traditional Wear": "和服·傳統服飾",
        "Fast Fashion": "快時尚",
        "Streetwear": "街頭潮流",
        "Shoes & Sneakers": "鞋·運動鞋",
        "Sportswear": "運動服",
        "Select Shop": "精選店",
        "Cakes & Pastries": "蛋糕·西點",
        "Crepes & Pancakes": "可麗餅·鬆餅",
        "Taiyaki & Dorayaki": "鯛魚燒·銅鑼燒",
        "Soft Serve & Ice Cream": "霜淇淋·冰淇淋",
        "Chocolate Specialist": "巧克力專門店",
        "Wagashi (Japanese Sweets)": "和菓子(日式點心)",
        "Bubble Tea & Drink Stand": "珍珠奶茶·飲料店",
        "Theme Cafe (Anime & Animals)": "主題咖啡廳(動漫·動物)",
        "Chain Cafe": "連鎖咖啡廳",
        "House-Roasted Coffee": "自家烘焙咖啡",
        "Retro Kissaten": "復古喫茶店",
        "Kimono Dressing & Hair Styling": "和服著裝·髮型設計",
        "Cut & Color": "剪髮·染髮",
        "Head Spa": "頭部護理",
        "Nail Salon": "美甲沙龍",
        "Eyelash Extensions": "睫毛嫁接",
        "Okonomiyaki & Monjayaki": "大阪燒·文字燒",
        "Soba & Udon": "蕎麥麵·烏龍麵",
        "Tempura & Tonkatsu": "天婦羅·炸豬排",
        "Indian Cuisine": "印度料理",
        "Chinese Cuisine": "中華料理",
        "Yakiniku & Horumon": "燒肉·內臟燒",
        "Korean Cuisine": "韓國料理",
        "Ramen": "拉麵",
        "Italian Cuisine": "義大利料理",
        "Sushi & Seafood": "壽司·海鮮",
        "100-Yen Shop": "百元商店",
        "Outlet": "暢貨中心",
        "Household Goods": "生活雜貨",
        "General Discount": "綜合折扣店",
        "Duty-Free Store": "免稅專門店",
        "Anma & Shiatsu": "按摩·指壓",
        "Reflexology (Foot Massage)": "足底按摩",
        "Quick Massage": "快速按摩",
        "Dry Head Spa": "乾式頭療",
        "Thai Massage": "泰式按摩",
        "Seitai & Chiropractic": "整體·脊椎矯正",
        "Oversized Luggage": "大型·超大行李",
        "Staffed Luggage Counter": "人工寄物櫃台",
        "Same-Day Hotel Delivery": "當日送達飯店",
        "Coin Lockers": "投幣式置物櫃",
        "Airport Delivery": "機場配送",
        "Fitness Gym": "健身房",
        "Bouldering": "抱石攀岩",
        "24-Hour Gym": "24小時健身房",
        "Yoga & Pilates": "瑜伽·皮拉提斯",
        "Pool & Swimming": "泳池·游泳",
        "Golf Range": "高爾夫練習場",
        "Large Bookstore": "大型書店",
        "Art & Photography Books": "藝術·攝影集",
        "Foreign & Multilingual Books": "外文·多語書籍",
        "Manga & Comics": "漫畫",
        "Antiquarian Books": "二手書店",
        "Supplements & Health Foods": "保健品·健康食品",
        "Medicine & Remedies": "藥品·常備藥",
        "Cosmetics & Skincare": "化妝品·護膚",
        "Hair & Body Care": "護髮·身體護理",
        "Baby Products": "嬰兒用品",
        "Gyudon (Beef Bowl)": "牛丼(牛肉蓋飯)",
        "Curry": "咖哩",
        "Fried Chicken": "炸雞",
        "Hamburgers": "漢堡",
        "Sandwiches & Bakery": "三明治·烘焙坊",
        "Standing Soba": "站著吃蕎麥麵",
        "Super Sento Bathhouse": "超級錢湯",
        "Natural Hot Spring": "天然溫泉",
        "Sauna": "三溫暖",
        "Private Bath": "包廂·包場浴池",
        "Esthetic Spa": "美容護理",
        "Ganbanyoku (Stone Sauna)": "岩盤浴",
        "Game Consoles & Software": "遊戲機·軟體",
        "Audio & Earphones": "音響·耳機",
        "PC & Phone Accessories": "電腦·手機周邊",
        "Beauty Appliances": "美容家電",
        "Cameras & Lenses": "相機·鏡頭",
        "Kitchen Appliances": "廚房家電",
        "Multiplex Cinema": "多廳影城",
        "Anime Screenings": "動畫電影放映",
        "Art-House Cinema": "藝術電影院·獨立影院",
        "IMAX & 4DX": "IMAX·4DX",
    },
    "th": {
        "Standing Bar": "บาร์ยืนดื่ม",
        "Whisky & Cocktail Bar": "บาร์วิสกี้·ค็อกเทล",
        "Izakaya": "อิซากายะ",
        "Craft Beer & Beer Bar": "คราฟต์เบียร์·เบียร์บาร์",
        "Wine Bar": "ไวน์บาร์",
        "Sake Bar": "บาร์สาเก",
        "Sports Bar": "สปอร์ตบาร์",
        "Free-Time & Late-Night Pack": "แพ็กฟรีไทม์·ดึก",
        "Solo Karaoke": "คาราโอเกะเดี่ยว",
        "Collab & Anime Room": "ห้องคอลแลบ·อนิเมะ",
        "Standard Karaoke Box": "ห้องคาราโอเกะทั่วไป",
        "Party Room": "ห้องปาร์ตี้",
        "Tickets & Services": "ตั๋ว·บริการต่าง ๆ",
        "Sweets & Ice Cream": "ขนมหวาน·ไอศกรีม",
        "Drinks & Alcohol": "เครื่องดื่ม·สุรา",
        "Daily Goods & Sundries": "ของใช้ประจำวัน·เบ็ดเตล็ด",
        "Bento & Onigiri": "เบนโตะ·ข้าวปั้น",
        "Used & Retro Games": "เกมมือสอง·เกมย้อนยุค",
        "CDs & Records": "ซีดี·แผ่นเสียง",
        "Trading Cards": "การ์ดสะสม",
        "Musical Instruments": "เครื่องดนตรี",
        "Figures & Hobby": "ฟิกเกอร์·งานอดิเรก",
        "Anime & Character Goods": "สินค้าอนิเมะ·คาแรกเตอร์",
        "Compact Car": "รถคอมแพกต์",
        "Luxury & Sports Car": "รถหรู·รถสปอร์ต",
        "Minivan (Large Group)": "รถตู้ (หลายคน)",
        "Car Sharing": "คาร์แชร์ริ่ง",
        "Electric Vehicle": "รถยนต์ไฟฟ้า",
        "Standard Car": "รถยนต์ทั่วไป",
        "Vintage & Secondhand": "เสื้อผ้ามือสอง·วินเทจ",
        "Kimono & Traditional Wear": "กิโมโน·ชุดประจำชาติ",
        "Fast Fashion": "ฟาสต์แฟชั่น",
        "Streetwear": "สตรีทแฟชั่น",
        "Shoes & Sneakers": "รองเท้า·สนีกเกอร์",
        "Sportswear": "ชุดกีฬา",
        "Select Shop": "เซเลกต์ช็อป",
        "Cakes & Pastries": "เค้ก·ขนมอบ",
        "Crepes & Pancakes": "เครป·แพนเค้ก",
        "Taiyaki & Dorayaki": "ไทยากิ·โดรายากิ",
        "Soft Serve & Ice Cream": "ซอฟต์ครีม·ไอศกรีม",
        "Chocolate Specialist": "ร้านช็อกโกแลตเฉพาะทาง",
        "Wagashi (Japanese Sweets)": "วากาชิ (ขนมญี่ปุ่น)",
        "Bubble Tea & Drink Stand": "ชานมไข่มุก·ร้านเครื่องดื่ม",
        "Theme Cafe (Anime & Animals)": "คาเฟ่ธีม (อนิเมะ·สัตว์)",
        "Chain Cafe": "คาเฟ่เชน",
        "House-Roasted Coffee": "กาแฟคั่วเอง",
        "Retro Kissaten": "คิสสะเต็นย้อนยุค",
        "Kimono Dressing & Hair Styling": "แต่งกิโมโน·จัดแต่งทรงผม",
        "Cut & Color": "ตัด·ทำสีผม",
        "Head Spa": "เฮดสปา",
        "Nail Salon": "ร้านทำเล็บ",
        "Eyelash Extensions": "ต่อขนตา",
        "Okonomiyaki & Monjayaki": "โอโคโนมิยากิ·มนจะยากิ",
        "Soba & Udon": "โซบะ·อุด้ง",
        "Tempura & Tonkatsu": "เทมปุระ·ทงคัตสึ",
        "Indian Cuisine": "อาหารอินเดีย",
        "Chinese Cuisine": "อาหารจีน",
        "Yakiniku & Horumon": "ยากินิกุ·เครื่องในย่าง",
        "Korean Cuisine": "อาหารเกาหลี",
        "Ramen": "ราเมง",
        "Italian Cuisine": "อาหารอิตาเลียน",
        "Sushi & Seafood": "ซูชิ·อาหารทะเล",
        "100-Yen Shop": "ร้าน 100 เยน",
        "Outlet": "เอาต์เล็ต",
        "Household Goods": "ของใช้ในบ้าน",
        "General Discount": "ร้านลดราคาทั่วไป",
        "Duty-Free Store": "ร้านปลอดภาษี",
        "Anma & Shiatsu": "อันมะ·ชิอัตสึ",
        "Reflexology (Foot Massage)": "นวดกดจุดฝ่าเท้า",
        "Quick Massage": "นวดด่วน",
        "Dry Head Spa": "ดรายเฮดสปา",
        "Thai Massage": "นวดแผนไทย",
        "Seitai & Chiropractic": "จัดกระดูก·ไคโรแพรกติก",
        "Oversized Luggage": "สัมภาระขนาดใหญ่พิเศษ",
        "Staffed Luggage Counter": "เคาน์เตอร์รับฝากสัมภาระ",
        "Same-Day Hotel Delivery": "ส่งถึงที่พักในวันเดียว",
        "Coin Lockers": "ล็อกเกอร์หยอดเหรียญ",
        "Airport Delivery": "ส่งไปสนามบิน",
        "Fitness Gym": "ฟิตเนสยิม",
        "Bouldering": "ปีนหน้าผาบอลเดอริง",
        "24-Hour Gym": "ยิม 24 ชั่วโมง",
        "Yoga & Pilates": "โยคะ·พิลาทิส",
        "Pool & Swimming": "สระว่ายน้ำ",
        "Golf Range": "สนามซ้อมกอล์ฟ",
        "Large Bookstore": "ร้านหนังสือขนาดใหญ่",
        "Art & Photography Books": "หนังสือศิลปะ·ภาพถ่าย",
        "Foreign & Multilingual Books": "หนังสือต่างประเทศ·หลายภาษา",
        "Manga & Comics": "มังงะ·การ์ตูน",
        "Antiquarian Books": "ร้านหนังสือเก่า",
        "Supplements & Health Foods": "อาหารเสริม·อาหารสุขภาพ",
        "Medicine & Remedies": "ยา·ยาสามัญประจำบ้าน",
        "Cosmetics & Skincare": "เครื่องสำอาง·สกินแคร์",
        "Hair & Body Care": "ดูแลเส้นผม·ผิวกาย",
        "Baby Products": "สินค้าสำหรับเด็กอ่อน",
        "Gyudon (Beef Bowl)": "กิวด้ง (ข้าวหน้าเนื้อ)",
        "Curry": "แกงกะหรี่",
        "Fried Chicken": "ไก่ทอด",
        "Hamburgers": "แฮมเบอร์เกอร์",
        "Sandwiches & Bakery": "แซนด์วิช·เบเกอรี่",
        "Standing Soba": "โซบะยืนกิน",
        "Super Sento Bathhouse": "โรงอาบน้ำซูเปอร์เซ็นโต",
        "Natural Hot Spring": "ออนเซนธรรมชาติ",
        "Sauna": "ซาวน่า",
        "Private Bath": "ห้องอาบน้ำส่วนตัว",
        "Esthetic Spa": "เอสเตติกสปา",
        "Ganbanyoku (Stone Sauna)": "กันบันโยกุ (อบหินร้อน)",
        "Game Consoles & Software": "เครื่องเกม·ซอฟต์แวร์",
        "Audio & Earphones": "เครื่องเสียง·หูฟัง",
        "PC & Phone Accessories": "อุปกรณ์เสริมพีซี·มือถือ",
        "Beauty Appliances": "เครื่องใช้ไฟฟ้าเพื่อความงาม",
        "Cameras & Lenses": "กล้อง·เลนส์",
        "Kitchen Appliances": "เครื่องใช้ไฟฟ้าในครัว",
        "Multiplex Cinema": "โรงภาพยนตร์มัลติเพล็กซ์",
        "Anime Screenings": "ฉายภาพยนตร์อนิเมะ",
        "Art-House Cinema": "โรงหนังอาร์ตเฮาส์",
        "IMAX & 4DX": "IMAX·4DX",
    },
    "vi": {
        "Standing Bar": "Quán nhậu đứng",
        "Whisky & Cocktail Bar": "Bar whisky & cocktail",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Bia thủ công & beer bar",
        "Wine Bar": "Bar rượu vang",
        "Sake Bar": "Bar rượu sake",
        "Sports Bar": "Bar thể thao",
        "Free-Time & Late-Night Pack": "Gói giờ tự do & khuya",
        "Solo Karaoke": "Karaoke một mình",
        "Collab & Anime Room": "Phòng collab & anime",
        "Standard Karaoke Box": "Phòng karaoke thường",
        "Party Room": "Phòng tiệc",
        "Tickets & Services": "Vé & dịch vụ",
        "Sweets & Ice Cream": "Đồ ngọt & kem",
        "Drinks & Alcohol": "Đồ uống & rượu bia",
        "Daily Goods & Sundries": "Đồ dùng hằng ngày",
        "Bento & Onigiri": "Cơm hộp & cơm nắm",
        "Used & Retro Games": "Game cũ & cổ điển",
        "CDs & Records": "CD & đĩa than",
        "Trading Cards": "Thẻ bài sưu tầm",
        "Musical Instruments": "Nhạc cụ",
        "Figures & Hobby": "Mô hình & sở thích",
        "Anime & Character Goods": "Đồ anime & nhân vật",
        "Compact Car": "Xe cỡ nhỏ",
        "Luxury & Sports Car": "Xe sang & xe thể thao",
        "Minivan (Large Group)": "Xe van (đông người)",
        "Car Sharing": "Chia sẻ xe",
        "Electric Vehicle": "Xe điện",
        "Standard Car": "Xe thường",
        "Vintage & Secondhand": "Đồ vintage & cũ",
        "Kimono & Traditional Wear": "Kimono & trang phục truyền thống",
        "Fast Fashion": "Thời trang nhanh",
        "Streetwear": "Thời trang đường phố",
        "Shoes & Sneakers": "Giày & sneaker",
        "Sportswear": "Đồ thể thao",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Bánh kem & bánh ngọt",
        "Crepes & Pancakes": "Crepe & pancake",
        "Taiyaki & Dorayaki": "Taiyaki & dorayaki",
        "Soft Serve & Ice Cream": "Kem tươi & kem",
        "Chocolate Specialist": "Cửa hàng sô cô la",
        "Wagashi (Japanese Sweets)": "Wagashi (bánh Nhật)",
        "Bubble Tea & Drink Stand": "Trà sữa & quầy đồ uống",
        "Theme Cafe (Anime & Animals)": "Cafe chủ đề (anime & thú cưng)",
        "Chain Cafe": "Cafe chuỗi",
        "House-Roasted Coffee": "Cà phê rang tại chỗ",
        "Retro Kissaten": "Kissaten cổ điển",
        "Kimono Dressing & Hair Styling": "Mặc kimono & làm tóc",
        "Cut & Color": "Cắt & nhuộm",
        "Head Spa": "Head spa",
        "Nail Salon": "Tiệm nail",
        "Eyelash Extensions": "Nối mi",
        "Okonomiyaki & Monjayaki": "Okonomiyaki & monjayaki",
        "Soba & Udon": "Soba & udon",
        "Tempura & Tonkatsu": "Tempura & tonkatsu",
        "Indian Cuisine": "Ẩm thực Ấn Độ",
        "Chinese Cuisine": "Ẩm thực Trung Hoa",
        "Yakiniku & Horumon": "Yakiniku & lòng nướng",
        "Korean Cuisine": "Ẩm thực Hàn Quốc",
        "Ramen": "Ramen",
        "Italian Cuisine": "Ẩm thực Ý",
        "Sushi & Seafood": "Sushi & hải sản",
        "100-Yen Shop": "Cửa hàng 100 yên",
        "Outlet": "Outlet",
        "Household Goods": "Đồ gia dụng",
        "General Discount": "Cửa hàng giảm giá tổng hợp",
        "Duty-Free Store": "Cửa hàng miễn thuế",
        "Anma & Shiatsu": "Anma & shiatsu",
        "Reflexology (Foot Massage)": "Bấm huyệt bàn chân",
        "Quick Massage": "Massage nhanh",
        "Dry Head Spa": "Head spa khô",
        "Thai Massage": "Massage Thái",
        "Seitai & Chiropractic": "Nắn chỉnh & trị liệu cột sống",
        "Oversized Luggage": "Hành lý quá khổ",
        "Staffed Luggage Counter": "Quầy giữ hành lý có nhân viên",
        "Same-Day Hotel Delivery": "Giao về khách sạn trong ngày",
        "Coin Lockers": "Tủ khóa xu",
        "Airport Delivery": "Giao ra sân bay",
        "Fitness Gym": "Phòng gym",
        "Bouldering": "Leo núi bouldering",
        "24-Hour Gym": "Gym 24 giờ",
        "Yoga & Pilates": "Yoga & pilates",
        "Pool & Swimming": "Hồ bơi & bơi lội",
        "Golf Range": "Sân tập golf",
        "Large Bookstore": "Nhà sách lớn",
        "Art & Photography Books": "Sách nghệ thuật & nhiếp ảnh",
        "Foreign & Multilingual Books": "Sách ngoại văn & đa ngữ",
        "Manga & Comics": "Manga & truyện tranh",
        "Antiquarian Books": "Hiệu sách cũ",
        "Supplements & Health Foods": "Thực phẩm bổ sung & sức khỏe",
        "Medicine & Remedies": "Thuốc & thuốc thường dùng",
        "Cosmetics & Skincare": "Mỹ phẩm & chăm sóc da",
        "Hair & Body Care": "Chăm sóc tóc & cơ thể",
        "Baby Products": "Đồ cho bé",
        "Gyudon (Beef Bowl)": "Gyudon (cơm bò)",
        "Curry": "Cà ri",
        "Fried Chicken": "Gà rán",
        "Hamburgers": "Hamburger",
        "Sandwiches & Bakery": "Sandwich & tiệm bánh",
        "Standing Soba": "Soba đứng ăn",
        "Super Sento Bathhouse": "Nhà tắm super sento",
        "Natural Hot Spring": "Suối nước nóng tự nhiên",
        "Sauna": "Sauna",
        "Private Bath": "Phòng tắm riêng",
        "Esthetic Spa": "Spa thẩm mỹ",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (tắm đá nóng)",
        "Game Consoles & Software": "Máy chơi game & phần mềm",
        "Audio & Earphones": "Âm thanh & tai nghe",
        "PC & Phone Accessories": "Phụ kiện PC & điện thoại",
        "Beauty Appliances": "Thiết bị làm đẹp",
        "Cameras & Lenses": "Máy ảnh & ống kính",
        "Kitchen Appliances": "Thiết bị nhà bếp",
        "Multiplex Cinema": "Rạp chiếu phim đa phòng",
        "Anime Screenings": "Chiếu phim anime",
        "Art-House Cinema": "Rạp phim nghệ thuật",
        "IMAX & 4DX": "IMAX & 4DX",
    },
    "fil": {
        "Standing Bar": "Standing Bar",
        "Whisky & Cocktail Bar": "Whisky & Cocktail Bar",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Craft Beer & Beer Bar",
        "Wine Bar": "Wine Bar",
        "Sake Bar": "Sake Bar",
        "Sports Bar": "Sports Bar",
        "Free-Time & Late-Night Pack": "Free-Time at Late-Night Pack",
        "Solo Karaoke": "Solo Karaoke",
        "Collab & Anime Room": "Collab at Anime Room",
        "Standard Karaoke Box": "Karaniwang Karaoke Box",
        "Party Room": "Party Room",
        "Tickets & Services": "Tiket at Serbisyo",
        "Sweets & Ice Cream": "Matamis at Ice Cream",
        "Drinks & Alcohol": "Inumin at Alak",
        "Daily Goods & Sundries": "Pang-araw-araw na Gamit",
        "Bento & Onigiri": "Bento at Onigiri",
        "Used & Retro Games": "Segunda-mano at Retro Games",
        "CDs & Records": "CD at Records",
        "Trading Cards": "Trading Cards",
        "Musical Instruments": "Instrumentong Pangmusika",
        "Figures & Hobby": "Figures at Hobby",
        "Anime & Character Goods": "Anime at Character Goods",
        "Compact Car": "Compact Car",
        "Luxury & Sports Car": "Luxury at Sports Car",
        "Minivan (Large Group)": "Minivan (Malaking Grupo)",
        "Car Sharing": "Car Sharing",
        "Electric Vehicle": "Sasakyang Elektriko",
        "Standard Car": "Karaniwang Sasakyan",
        "Vintage & Secondhand": "Vintage at Segunda-mano",
        "Kimono & Traditional Wear": "Kimono at Tradisyonal na Damit",
        "Fast Fashion": "Fast Fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Sapatos at Sneakers",
        "Sportswear": "Damit Pang-sports",
        "Select Shop": "Select Shop",
        "Cakes & Pastries": "Cake at Pastry",
        "Crepes & Pancakes": "Crepe at Pancake",
        "Taiyaki & Dorayaki": "Taiyaki at Dorayaki",
        "Soft Serve & Ice Cream": "Soft Serve at Ice Cream",
        "Chocolate Specialist": "Espesyalista sa Tsokolate",
        "Wagashi (Japanese Sweets)": "Wagashi (Matamis na Hapon)",
        "Bubble Tea & Drink Stand": "Bubble Tea at Drink Stand",
        "Theme Cafe (Anime & Animals)": "Theme Cafe (Anime at Hayop)",
        "Chain Cafe": "Chain Cafe",
        "House-Roasted Coffee": "Sariling-Roast na Kape",
        "Retro Kissaten": "Retro Kissaten",
        "Kimono Dressing & Hair Styling": "Pagsusuot ng Kimono at Hair Styling",
        "Cut & Color": "Gupit at Kulay",
        "Head Spa": "Head Spa",
        "Nail Salon": "Nail Salon",
        "Eyelash Extensions": "Eyelash Extensions",
        "Okonomiyaki & Monjayaki": "Okonomiyaki at Monjayaki",
        "Soba & Udon": "Soba at Udon",
        "Tempura & Tonkatsu": "Tempura at Tonkatsu",
        "Indian Cuisine": "Lutong Indian",
        "Chinese Cuisine": "Lutong Intsik",
        "Yakiniku & Horumon": "Yakiniku at Horumon",
        "Korean Cuisine": "Lutong Korean",
        "Ramen": "Ramen",
        "Italian Cuisine": "Lutong Italyano",
        "Sushi & Seafood": "Sushi at Seafood",
        "100-Yen Shop": "100-Yen Shop",
        "Outlet": "Outlet",
        "Household Goods": "Gamit sa Bahay",
        "General Discount": "Pangkalahatang Discount",
        "Duty-Free Store": "Duty-Free Store",
        "Anma & Shiatsu": "Anma at Shiatsu",
        "Reflexology (Foot Massage)": "Reflexology (Paa Massage)",
        "Quick Massage": "Mabilisang Massage",
        "Dry Head Spa": "Dry Head Spa",
        "Thai Massage": "Thai Massage",
        "Seitai & Chiropractic": "Seitai at Chiropractic",
        "Oversized Luggage": "Malalaking Bagahe",
        "Staffed Luggage Counter": "Luggage Counter na May Tauhan",
        "Same-Day Hotel Delivery": "Same-Day Delivery sa Hotel",
        "Coin Lockers": "Coin Lockers",
        "Airport Delivery": "Delivery sa Airport",
        "Fitness Gym": "Fitness Gym",
        "Bouldering": "Bouldering",
        "24-Hour Gym": "24-Oras na Gym",
        "Yoga & Pilates": "Yoga at Pilates",
        "Pool & Swimming": "Pool at Paglangoy",
        "Golf Range": "Golf Range",
        "Large Bookstore": "Malaking Bookstore",
        "Art & Photography Books": "Art at Photography Books",
        "Foreign & Multilingual Books": "Dayuhan at Multilingual na Libro",
        "Manga & Comics": "Manga at Comics",
        "Antiquarian Books": "Lumang Libro",
        "Supplements & Health Foods": "Supplements at Health Foods",
        "Medicine & Remedies": "Gamot at Remedyo",
        "Cosmetics & Skincare": "Cosmetics at Skincare",
        "Hair & Body Care": "Hair at Body Care",
        "Baby Products": "Gamit ng Sanggol",
        "Gyudon (Beef Bowl)": "Gyudon (Beef Bowl)",
        "Curry": "Curry",
        "Fried Chicken": "Fried Chicken",
        "Hamburgers": "Hamburger",
        "Sandwiches & Bakery": "Sandwich at Bakery",
        "Standing Soba": "Standing Soba",
        "Super Sento Bathhouse": "Super Sento Bathhouse",
        "Natural Hot Spring": "Natural na Hot Spring",
        "Sauna": "Sauna",
        "Private Bath": "Pribadong Paliguan",
        "Esthetic Spa": "Esthetic Spa",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (Stone Sauna)",
        "Game Consoles & Software": "Game Console at Software",
        "Audio & Earphones": "Audio at Earphones",
        "PC & Phone Accessories": "PC at Phone Accessories",
        "Beauty Appliances": "Beauty Appliances",
        "Cameras & Lenses": "Camera at Lens",
        "Kitchen Appliances": "Kitchen Appliances",
        "Multiplex Cinema": "Multiplex Cinema",
        "Anime Screenings": "Anime Screenings",
        "Art-House Cinema": "Art-House Cinema",
        "IMAX & 4DX": "IMAX at 4DX",
    },
    "hi": {
        "Standing Bar": "खड़े होकर पीने का बार",
        "Whisky & Cocktail Bar": "व्हिस्की·कॉकटेल बार",
        "Izakaya": "इज़ाकाया",
        "Craft Beer & Beer Bar": "क्राफ्ट बीयर·बीयर बार",
        "Wine Bar": "वाइन बार",
        "Sake Bar": "साके बार",
        "Sports Bar": "स्पोर्ट्स बार",
        "Free-Time & Late-Night Pack": "फ्री-टाइम·देर रात पैक",
        "Solo Karaoke": "एकल कराओके",
        "Collab & Anime Room": "कोलैब·एनीमे रूम",
        "Standard Karaoke Box": "सामान्य कराओके बॉक्स",
        "Party Room": "पार्टी रूम",
        "Tickets & Services": "टिकट·सेवाएँ",
        "Sweets & Ice Cream": "मिठाई·आइसक्रीम",
        "Drinks & Alcohol": "पेय·शराब",
        "Daily Goods & Sundries": "रोज़मर्रा का सामान",
        "Bento & Onigiri": "बेंटो·ओनिगिरी",
        "Used & Retro Games": "पुराने·रेट्रो गेम",
        "CDs & Records": "सीडी·रिकॉर्ड",
        "Trading Cards": "ट्रेडिंग कार्ड",
        "Musical Instruments": "वाद्य यंत्र",
        "Figures & Hobby": "फिगर·हॉबी",
        "Anime & Character Goods": "एनीमे·कैरेक्टर सामान",
        "Compact Car": "कॉम्पैक्ट कार",
        "Luxury & Sports Car": "लक्ज़री·स्पोर्ट्स कार",
        "Minivan (Large Group)": "मिनीवैन (बड़ा समूह)",
        "Car Sharing": "कार शेयरिंग",
        "Electric Vehicle": "इलेक्ट्रिक वाहन",
        "Standard Car": "सामान्य कार",
        "Vintage & Secondhand": "विंटेज·पुराने कपड़े",
        "Kimono & Traditional Wear": "किमोनो·पारंपरिक परिधान",
        "Fast Fashion": "फास्ट फैशन",
        "Streetwear": "स्ट्रीटवियर",
        "Shoes & Sneakers": "जूते·स्नीकर्स",
        "Sportswear": "स्पोर्ट्सवियर",
        "Select Shop": "सेलेक्ट शॉप",
        "Cakes & Pastries": "केक·पेस्ट्री",
        "Crepes & Pancakes": "क्रेप·पैनकेक",
        "Taiyaki & Dorayaki": "तायाकी·दोरायाकी",
        "Soft Serve & Ice Cream": "सॉफ्ट सर्व·आइसक्रीम",
        "Chocolate Specialist": "चॉकलेट विशेषज्ञ",
        "Wagashi (Japanese Sweets)": "वागाशी (जापानी मिठाई)",
        "Bubble Tea & Drink Stand": "बबल टी·ड्रिंक स्टैंड",
        "Theme Cafe (Anime & Animals)": "थीम कैफे (एनीमे·जानवर)",
        "Chain Cafe": "चेन कैफे",
        "House-Roasted Coffee": "स्वयं भुनी कॉफ़ी",
        "Retro Kissaten": "रेट्रो किस्साटेन",
        "Kimono Dressing & Hair Styling": "किमोनो पहनाना·हेयर स्टाइलिंग",
        "Cut & Color": "कट·कलर",
        "Head Spa": "हेड स्पा",
        "Nail Salon": "नेल सैलून",
        "Eyelash Extensions": "आईलैश एक्सटेंशन",
        "Okonomiyaki & Monjayaki": "ओकोनोमियाकी·मोनजायाकी",
        "Soba & Udon": "सोबा·उदोन",
        "Tempura & Tonkatsu": "टेम्पुरा·टोंकात्सु",
        "Indian Cuisine": "भारतीय व्यंजन",
        "Chinese Cuisine": "चीनी व्यंजन",
        "Yakiniku & Horumon": "याकिनिकु·होरुमोन",
        "Korean Cuisine": "कोरियाई व्यंजन",
        "Ramen": "रामेन",
        "Italian Cuisine": "इतालवी व्यंजन",
        "Sushi & Seafood": "सुशी·समुद्री भोजन",
        "100-Yen Shop": "100-येन शॉप",
        "Outlet": "आउटलेट",
        "Household Goods": "घरेलू सामान",
        "General Discount": "सामान्य डिस्काउंट",
        "Duty-Free Store": "ड्यूटी-फ्री स्टोर",
        "Anma & Shiatsu": "अनमा·शियात्सु",
        "Reflexology (Foot Massage)": "रिफ्लेक्सोलॉजी (पैर की मालिश)",
        "Quick Massage": "क्विक मसाज",
        "Dry Head Spa": "ड्राई हेड स्पा",
        "Thai Massage": "थाई मसाज",
        "Seitai & Chiropractic": "सेइताई·कायरोप्रैक्टिक",
        "Oversized Luggage": "बड़ा·अतिरिक्त सामान",
        "Staffed Luggage Counter": "कर्मचारी युक्त सामान काउंटर",
        "Same-Day Hotel Delivery": "उसी दिन होटल डिलीवरी",
        "Coin Lockers": "कॉइन लॉकर",
        "Airport Delivery": "हवाई अड्डा डिलीवरी",
        "Fitness Gym": "फिटनेस जिम",
        "Bouldering": "बोल्डरिंग",
        "24-Hour Gym": "24-घंटे जिम",
        "Yoga & Pilates": "योग·पिलेट्स",
        "Pool & Swimming": "पूल·तैराकी",
        "Golf Range": "गोल्फ रेंज",
        "Large Bookstore": "बड़ी किताबों की दुकान",
        "Art & Photography Books": "कला·फोटोग्राफी पुस्तकें",
        "Foreign & Multilingual Books": "विदेशी·बहुभाषी पुस्तकें",
        "Manga & Comics": "मंगा·कॉमिक्स",
        "Antiquarian Books": "पुरानी किताबों की दुकान",
        "Supplements & Health Foods": "सप्लीमेंट·स्वास्थ्य आहार",
        "Medicine & Remedies": "दवाइयाँ·घरेलू औषधि",
        "Cosmetics & Skincare": "सौंदर्य प्रसाधन·स्किनकेयर",
        "Hair & Body Care": "हेयर·बॉडी केयर",
        "Baby Products": "शिशु उत्पाद",
        "Gyudon (Beef Bowl)": "ग्यूदोन (बीफ बाउल)",
        "Curry": "करी",
        "Fried Chicken": "फ्राइड चिकन",
        "Hamburgers": "हैमबर्गर",
        "Sandwiches & Bakery": "सैंडविच·बेकरी",
        "Standing Soba": "खड़े होकर खाने वाला सोबा",
        "Super Sento Bathhouse": "सुपर सेंटो स्नानगृह",
        "Natural Hot Spring": "प्राकृतिक गर्म झरना",
        "Sauna": "सॉना",
        "Private Bath": "निजी स्नान",
        "Esthetic Spa": "एस्थेटिक स्पा",
        "Ganbanyoku (Stone Sauna)": "गनबन्योकु (पत्थर सॉना)",
        "Game Consoles & Software": "गेम कंसोल·सॉफ्टवेयर",
        "Audio & Earphones": "ऑडियो·इयरफोन",
        "PC & Phone Accessories": "पीसी·फोन एक्सेसरीज़",
        "Beauty Appliances": "सौंदर्य उपकरण",
        "Cameras & Lenses": "कैमरा·लेंस",
        "Kitchen Appliances": "रसोई उपकरण",
        "Multiplex Cinema": "मल्टीप्लेक्स सिनेमा",
        "Anime Screenings": "एनीमे स्क्रीनिंग",
        "Art-House Cinema": "आर्ट-हाउस सिनेमा",
        "IMAX & 4DX": "IMAX·4DX",
    },
    "es": {
        "Standing Bar": "Bar de pie",
        "Whisky & Cocktail Bar": "Bar de whisky y cócteles",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Cerveza artesanal y bar de cerveza",
        "Wine Bar": "Bar de vinos",
        "Sake Bar": "Bar de sake",
        "Sports Bar": "Bar deportivo",
        "Free-Time & Late-Night Pack": "Paquete libre y nocturno",
        "Solo Karaoke": "Karaoke individual",
        "Collab & Anime Room": "Sala colaboración y anime",
        "Standard Karaoke Box": "Karaoke estándar",
        "Party Room": "Sala de fiestas",
        "Tickets & Services": "Entradas y servicios",
        "Sweets & Ice Cream": "Dulces y helados",
        "Drinks & Alcohol": "Bebidas y alcohol",
        "Daily Goods & Sundries": "Artículos de uso diario",
        "Bento & Onigiri": "Bento y onigiri",
        "Used & Retro Games": "Juegos usados y retro",
        "CDs & Records": "CD y vinilos",
        "Trading Cards": "Cartas coleccionables",
        "Musical Instruments": "Instrumentos musicales",
        "Figures & Hobby": "Figuras y hobby",
        "Anime & Character Goods": "Artículos de anime y personajes",
        "Compact Car": "Coche compacto",
        "Luxury & Sports Car": "Coche de lujo y deportivo",
        "Minivan (Large Group)": "Monovolumen (grupo grande)",
        "Car Sharing": "Coche compartido",
        "Electric Vehicle": "Vehículo eléctrico",
        "Standard Car": "Coche estándar",
        "Vintage & Secondhand": "Vintage y segunda mano",
        "Kimono & Traditional Wear": "Kimono y ropa tradicional",
        "Fast Fashion": "Moda rápida",
        "Streetwear": "Ropa urbana",
        "Shoes & Sneakers": "Zapatos y zapatillas",
        "Sportswear": "Ropa deportiva",
        "Select Shop": "Tienda select",
        "Cakes & Pastries": "Pasteles y repostería",
        "Crepes & Pancakes": "Crepes y tortitas",
        "Taiyaki & Dorayaki": "Taiyaki y dorayaki",
        "Soft Serve & Ice Cream": "Helado soft y helados",
        "Chocolate Specialist": "Chocolatería",
        "Wagashi (Japanese Sweets)": "Wagashi (dulces japoneses)",
        "Bubble Tea & Drink Stand": "Bubble tea y puesto de bebidas",
        "Theme Cafe (Anime & Animals)": "Café temático (anime y animales)",
        "Chain Cafe": "Café de cadena",
        "House-Roasted Coffee": "Café tostado en casa",
        "Retro Kissaten": "Kissaten retro",
        "Kimono Dressing & Hair Styling": "Vestido de kimono y peinado",
        "Cut & Color": "Corte y color",
        "Head Spa": "Head spa",
        "Nail Salon": "Salón de uñas",
        "Eyelash Extensions": "Extensiones de pestañas",
        "Okonomiyaki & Monjayaki": "Okonomiyaki y monjayaki",
        "Soba & Udon": "Soba y udon",
        "Tempura & Tonkatsu": "Tempura y tonkatsu",
        "Indian Cuisine": "Cocina india",
        "Chinese Cuisine": "Cocina china",
        "Yakiniku & Horumon": "Yakiniku y horumon",
        "Korean Cuisine": "Cocina coreana",
        "Ramen": "Ramen",
        "Italian Cuisine": "Cocina italiana",
        "Sushi & Seafood": "Sushi y marisco",
        "100-Yen Shop": "Tienda de 100 yenes",
        "Outlet": "Outlet",
        "Household Goods": "Artículos para el hogar",
        "General Discount": "Descuento general",
        "Duty-Free Store": "Tienda libre de impuestos",
        "Anma & Shiatsu": "Anma y shiatsu",
        "Reflexology (Foot Massage)": "Reflexología (masaje de pies)",
        "Quick Massage": "Masaje rápido",
        "Dry Head Spa": "Head spa en seco",
        "Thai Massage": "Masaje tailandés",
        "Seitai & Chiropractic": "Seitai y quiropráctica",
        "Oversized Luggage": "Equipaje de gran tamaño",
        "Staffed Luggage Counter": "Mostrador de equipaje atendido",
        "Same-Day Hotel Delivery": "Entrega al hotel el mismo día",
        "Coin Lockers": "Taquillas",
        "Airport Delivery": "Entrega al aeropuerto",
        "Fitness Gym": "Gimnasio",
        "Bouldering": "Búlder",
        "24-Hour Gym": "Gimnasio 24 horas",
        "Yoga & Pilates": "Yoga y pilates",
        "Pool & Swimming": "Piscina y natación",
        "Golf Range": "Campo de prácticas de golf",
        "Large Bookstore": "Gran librería",
        "Art & Photography Books": "Libros de arte y fotografía",
        "Foreign & Multilingual Books": "Libros extranjeros y multilingües",
        "Manga & Comics": "Manga y cómics",
        "Antiquarian Books": "Librería de viejo",
        "Supplements & Health Foods": "Suplementos y alimentos saludables",
        "Medicine & Remedies": "Medicamentos y remedios",
        "Cosmetics & Skincare": "Cosmética y cuidado de la piel",
        "Hair & Body Care": "Cuidado del cabello y el cuerpo",
        "Baby Products": "Productos para bebé",
        "Gyudon (Beef Bowl)": "Gyudon (bol de ternera)",
        "Curry": "Curry",
        "Fried Chicken": "Pollo frito",
        "Hamburgers": "Hamburguesas",
        "Sandwiches & Bakery": "Sándwiches y panadería",
        "Standing Soba": "Soba de pie",
        "Super Sento Bathhouse": "Baños super sento",
        "Natural Hot Spring": "Aguas termales naturales",
        "Sauna": "Sauna",
        "Private Bath": "Baño privado",
        "Esthetic Spa": "Spa estético",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (sauna de piedra)",
        "Game Consoles & Software": "Consolas y software",
        "Audio & Earphones": "Audio y auriculares",
        "PC & Phone Accessories": "Accesorios de PC y móvil",
        "Beauty Appliances": "Electrodomésticos de belleza",
        "Cameras & Lenses": "Cámaras y objetivos",
        "Kitchen Appliances": "Electrodomésticos de cocina",
        "Multiplex Cinema": "Cine multiplex",
        "Anime Screenings": "Proyecciones de anime",
        "Art-House Cinema": "Cine de autor",
        "IMAX & 4DX": "IMAX y 4DX",
    },
    "pt": {
        "Standing Bar": "Bar de pé",
        "Whisky & Cocktail Bar": "Bar de uísque e coquetéis",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Cerveja artesanal e bar de cerveja",
        "Wine Bar": "Bar de vinhos",
        "Sake Bar": "Bar de saquê",
        "Sports Bar": "Bar esportivo",
        "Free-Time & Late-Night Pack": "Pacote livre e noturno",
        "Solo Karaoke": "Karaokê individual",
        "Collab & Anime Room": "Sala colab e anime",
        "Standard Karaoke Box": "Karaokê padrão",
        "Party Room": "Sala de festas",
        "Tickets & Services": "Ingressos e serviços",
        "Sweets & Ice Cream": "Doces e sorvetes",
        "Drinks & Alcohol": "Bebidas e álcool",
        "Daily Goods & Sundries": "Artigos do dia a dia",
        "Bento & Onigiri": "Bentô e onigiri",
        "Used & Retro Games": "Jogos usados e retrô",
        "CDs & Records": "CDs e discos",
        "Trading Cards": "Cartas colecionáveis",
        "Musical Instruments": "Instrumentos musicais",
        "Figures & Hobby": "Figuras e hobby",
        "Anime & Character Goods": "Produtos de anime e personagens",
        "Compact Car": "Carro compacto",
        "Luxury & Sports Car": "Carro de luxo e esportivo",
        "Minivan (Large Group)": "Minivan (grupo grande)",
        "Car Sharing": "Compartilhamento de carro",
        "Electric Vehicle": "Veículo elétrico",
        "Standard Car": "Carro comum",
        "Vintage & Secondhand": "Vintage e usados",
        "Kimono & Traditional Wear": "Quimono e traje tradicional",
        "Fast Fashion": "Fast fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Sapatos e tênis",
        "Sportswear": "Roupa esportiva",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Bolos e confeitaria",
        "Crepes & Pancakes": "Crepes e panquecas",
        "Taiyaki & Dorayaki": "Taiyaki e dorayaki",
        "Soft Serve & Ice Cream": "Sorvete soft e sorvetes",
        "Chocolate Specialist": "Chocolateria",
        "Wagashi (Japanese Sweets)": "Wagashi (doces japoneses)",
        "Bubble Tea & Drink Stand": "Bubble tea e quiosque de bebidas",
        "Theme Cafe (Anime & Animals)": "Café temático (anime e animais)",
        "Chain Cafe": "Café de rede",
        "House-Roasted Coffee": "Café torrado na casa",
        "Retro Kissaten": "Kissaten retrô",
        "Kimono Dressing & Hair Styling": "Vestir quimono e penteado",
        "Cut & Color": "Corte e cor",
        "Head Spa": "Head spa",
        "Nail Salon": "Salão de unhas",
        "Eyelash Extensions": "Extensão de cílios",
        "Okonomiyaki & Monjayaki": "Okonomiyaki e monjayaki",
        "Soba & Udon": "Soba e udon",
        "Tempura & Tonkatsu": "Tempurá e tonkatsu",
        "Indian Cuisine": "Culinária indiana",
        "Chinese Cuisine": "Culinária chinesa",
        "Yakiniku & Horumon": "Yakiniku e horumon",
        "Korean Cuisine": "Culinária coreana",
        "Ramen": "Ramen",
        "Italian Cuisine": "Culinária italiana",
        "Sushi & Seafood": "Sushi e frutos do mar",
        "100-Yen Shop": "Loja de 100 ienes",
        "Outlet": "Outlet",
        "Household Goods": "Artigos domésticos",
        "General Discount": "Loja de descontos geral",
        "Duty-Free Store": "Loja duty-free",
        "Anma & Shiatsu": "Anma e shiatsu",
        "Reflexology (Foot Massage)": "Reflexologia (massagem nos pés)",
        "Quick Massage": "Massagem rápida",
        "Dry Head Spa": "Head spa seco",
        "Thai Massage": "Massagem tailandesa",
        "Seitai & Chiropractic": "Seitai e quiropraxia",
        "Oversized Luggage": "Bagagem de grande porte",
        "Staffed Luggage Counter": "Balcão de bagagem com atendente",
        "Same-Day Hotel Delivery": "Entrega no hotel no mesmo dia",
        "Coin Lockers": "Armários com moeda",
        "Airport Delivery": "Entrega no aeroporto",
        "Fitness Gym": "Academia",
        "Bouldering": "Boulder",
        "24-Hour Gym": "Academia 24 horas",
        "Yoga & Pilates": "Yoga e pilates",
        "Pool & Swimming": "Piscina e natação",
        "Golf Range": "Campo de treino de golfe",
        "Large Bookstore": "Livraria grande",
        "Art & Photography Books": "Livros de arte e fotografia",
        "Foreign & Multilingual Books": "Livros estrangeiros e multilíngues",
        "Manga & Comics": "Mangá e quadrinhos",
        "Antiquarian Books": "Sebo",
        "Supplements & Health Foods": "Suplementos e alimentos saudáveis",
        "Medicine & Remedies": "Medicamentos e remédios",
        "Cosmetics & Skincare": "Cosméticos e cuidados com a pele",
        "Hair & Body Care": "Cuidados com cabelo e corpo",
        "Baby Products": "Produtos para bebê",
        "Gyudon (Beef Bowl)": "Gyudon (tigela de carne)",
        "Curry": "Curry",
        "Fried Chicken": "Frango frito",
        "Hamburgers": "Hambúrgueres",
        "Sandwiches & Bakery": "Sanduíches e padaria",
        "Standing Soba": "Soba em pé",
        "Super Sento Bathhouse": "Casa de banho super sento",
        "Natural Hot Spring": "Fonte termal natural",
        "Sauna": "Sauna",
        "Private Bath": "Banho privativo",
        "Esthetic Spa": "Spa estético",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (sauna de pedra)",
        "Game Consoles & Software": "Consoles e software",
        "Audio & Earphones": "Áudio e fones",
        "PC & Phone Accessories": "Acessórios de PC e celular",
        "Beauty Appliances": "Eletrodomésticos de beleza",
        "Cameras & Lenses": "Câmeras e lentes",
        "Kitchen Appliances": "Eletrodomésticos de cozinha",
        "Multiplex Cinema": "Cinema multiplex",
        "Anime Screenings": "Sessões de anime",
        "Art-House Cinema": "Cinema de arte",
        "IMAX & 4DX": "IMAX e 4DX",
    },
    "fr": {
        "Standing Bar": "Bar debout",
        "Whisky & Cocktail Bar": "Bar à whisky et cocktails",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Bière artisanale et bar à bière",
        "Wine Bar": "Bar à vin",
        "Sake Bar": "Bar à saké",
        "Sports Bar": "Bar sportif",
        "Free-Time & Late-Night Pack": "Forfait libre et nocturne",
        "Solo Karaoke": "Karaoké solo",
        "Collab & Anime Room": "Salle collab et anime",
        "Standard Karaoke Box": "Box karaoké standard",
        "Party Room": "Salle de fête",
        "Tickets & Services": "Billets et services",
        "Sweets & Ice Cream": "Douceurs et glaces",
        "Drinks & Alcohol": "Boissons et alcools",
        "Daily Goods & Sundries": "Articles du quotidien",
        "Bento & Onigiri": "Bentō et onigiri",
        "Used & Retro Games": "Jeux d'occasion et rétro",
        "CDs & Records": "CD et vinyles",
        "Trading Cards": "Cartes à collectionner",
        "Musical Instruments": "Instruments de musique",
        "Figures & Hobby": "Figurines et loisirs",
        "Anime & Character Goods": "Produits anime et personnages",
        "Compact Car": "Voiture compacte",
        "Luxury & Sports Car": "Voiture de luxe et sportive",
        "Minivan (Large Group)": "Monospace (grand groupe)",
        "Car Sharing": "Autopartage",
        "Electric Vehicle": "Véhicule électrique",
        "Standard Car": "Voiture standard",
        "Vintage & Secondhand": "Vintage et seconde main",
        "Kimono & Traditional Wear": "Kimono et tenue traditionnelle",
        "Fast Fashion": "Fast fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Chaussures et baskets",
        "Sportswear": "Vêtements de sport",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Gâteaux et pâtisseries",
        "Crepes & Pancakes": "Crêpes et pancakes",
        "Taiyaki & Dorayaki": "Taiyaki et dorayaki",
        "Soft Serve & Ice Cream": "Glace à l'italienne et glaces",
        "Chocolate Specialist": "Chocolaterie",
        "Wagashi (Japanese Sweets)": "Wagashi (pâtisseries japonaises)",
        "Bubble Tea & Drink Stand": "Bubble tea et stand de boissons",
        "Theme Cafe (Anime & Animals)": "Café à thème (anime et animaux)",
        "Chain Cafe": "Café de chaîne",
        "House-Roasted Coffee": "Café torréfié maison",
        "Retro Kissaten": "Kissaten rétro",
        "Kimono Dressing & Hair Styling": "Habillage kimono et coiffure",
        "Cut & Color": "Coupe et couleur",
        "Head Spa": "Head spa",
        "Nail Salon": "Salon d'ongles",
        "Eyelash Extensions": "Extensions de cils",
        "Okonomiyaki & Monjayaki": "Okonomiyaki et monjayaki",
        "Soba & Udon": "Soba et udon",
        "Tempura & Tonkatsu": "Tempura et tonkatsu",
        "Indian Cuisine": "Cuisine indienne",
        "Chinese Cuisine": "Cuisine chinoise",
        "Yakiniku & Horumon": "Yakiniku et horumon",
        "Korean Cuisine": "Cuisine coréenne",
        "Ramen": "Ramen",
        "Italian Cuisine": "Cuisine italienne",
        "Sushi & Seafood": "Sushi et fruits de mer",
        "100-Yen Shop": "Boutique à 100 yens",
        "Outlet": "Outlet",
        "Household Goods": "Articles ménagers",
        "General Discount": "Discount généraliste",
        "Duty-Free Store": "Boutique hors taxes",
        "Anma & Shiatsu": "Anma et shiatsu",
        "Reflexology (Foot Massage)": "Réflexologie (massage des pieds)",
        "Quick Massage": "Massage express",
        "Dry Head Spa": "Head spa à sec",
        "Thai Massage": "Massage thaï",
        "Seitai & Chiropractic": "Seitai et chiropraxie",
        "Oversized Luggage": "Bagages hors format",
        "Staffed Luggage Counter": "Comptoir bagages avec personnel",
        "Same-Day Hotel Delivery": "Livraison à l'hôtel le jour même",
        "Coin Lockers": "Casiers à pièces",
        "Airport Delivery": "Livraison à l'aéroport",
        "Fitness Gym": "Salle de fitness",
        "Bouldering": "Escalade de bloc",
        "24-Hour Gym": "Salle 24 h/24",
        "Yoga & Pilates": "Yoga et pilates",
        "Pool & Swimming": "Piscine et natation",
        "Golf Range": "Practice de golf",
        "Large Bookstore": "Grande librairie",
        "Art & Photography Books": "Livres d'art et de photographie",
        "Foreign & Multilingual Books": "Livres étrangers et multilingues",
        "Manga & Comics": "Manga et BD",
        "Antiquarian Books": "Librairie ancienne",
        "Supplements & Health Foods": "Compléments et aliments santé",
        "Medicine & Remedies": "Médicaments et remèdes",
        "Cosmetics & Skincare": "Cosmétiques et soins de la peau",
        "Hair & Body Care": "Soins cheveux et corps",
        "Baby Products": "Produits pour bébé",
        "Gyudon (Beef Bowl)": "Gyudon (bol de bœuf)",
        "Curry": "Curry",
        "Fried Chicken": "Poulet frit",
        "Hamburgers": "Hamburgers",
        "Sandwiches & Bakery": "Sandwichs et boulangerie",
        "Standing Soba": "Soba debout",
        "Super Sento Bathhouse": "Bains super sento",
        "Natural Hot Spring": "Source chaude naturelle",
        "Sauna": "Sauna",
        "Private Bath": "Bain privatif",
        "Esthetic Spa": "Spa esthétique",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (sauna de pierre)",
        "Game Consoles & Software": "Consoles et logiciels",
        "Audio & Earphones": "Audio et écouteurs",
        "PC & Phone Accessories": "Accessoires PC et téléphone",
        "Beauty Appliances": "Appareils de beauté",
        "Cameras & Lenses": "Appareils photo et objectifs",
        "Kitchen Appliances": "Électroménager de cuisine",
        "Multiplex Cinema": "Cinéma multiplexe",
        "Anime Screenings": "Projections d'anime",
        "Art-House Cinema": "Cinéma d'art et d'essai",
        "IMAX & 4DX": "IMAX et 4DX",
    },
    "de": {
        "Standing Bar": "Stehbar",
        "Whisky & Cocktail Bar": "Whisky- & Cocktailbar",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Craft Beer & Bierbar",
        "Wine Bar": "Weinbar",
        "Sake Bar": "Sake-Bar",
        "Sports Bar": "Sportsbar",
        "Free-Time & Late-Night Pack": "Freizeit- & Spätnacht-Paket",
        "Solo Karaoke": "Solo-Karaoke",
        "Collab & Anime Room": "Collab- & Anime-Raum",
        "Standard Karaoke Box": "Standard-Karaokebox",
        "Party Room": "Partyraum",
        "Tickets & Services": "Tickets & Services",
        "Sweets & Ice Cream": "Süßes & Eis",
        "Drinks & Alcohol": "Getränke & Alkohol",
        "Daily Goods & Sundries": "Alltagswaren & Sonstiges",
        "Bento & Onigiri": "Bento & Onigiri",
        "Used & Retro Games": "Gebrauchte & Retro-Spiele",
        "CDs & Records": "CDs & Schallplatten",
        "Trading Cards": "Sammelkarten",
        "Musical Instruments": "Musikinstrumente",
        "Figures & Hobby": "Figuren & Hobby",
        "Anime & Character Goods": "Anime- & Charakterartikel",
        "Compact Car": "Kompaktwagen",
        "Luxury & Sports Car": "Luxus- & Sportwagen",
        "Minivan (Large Group)": "Minivan (große Gruppe)",
        "Car Sharing": "Carsharing",
        "Electric Vehicle": "Elektrofahrzeug",
        "Standard Car": "Standardwagen",
        "Vintage & Secondhand": "Vintage & Secondhand",
        "Kimono & Traditional Wear": "Kimono & Trachten",
        "Fast Fashion": "Fast Fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Schuhe & Sneaker",
        "Sportswear": "Sportbekleidung",
        "Select Shop": "Select Shop",
        "Cakes & Pastries": "Kuchen & Gebäck",
        "Crepes & Pancakes": "Crêpes & Pancakes",
        "Taiyaki & Dorayaki": "Taiyaki & Dorayaki",
        "Soft Serve & Ice Cream": "Softeis & Eis",
        "Chocolate Specialist": "Schokoladengeschäft",
        "Wagashi (Japanese Sweets)": "Wagashi (japanische Süßigkeiten)",
        "Bubble Tea & Drink Stand": "Bubble Tea & Getränkestand",
        "Theme Cafe (Anime & Animals)": "Themen-Café (Anime & Tiere)",
        "Chain Cafe": "Ketten-Café",
        "House-Roasted Coffee": "Hausgerösteter Kaffee",
        "Retro Kissaten": "Retro-Kissaten",
        "Kimono Dressing & Hair Styling": "Kimono-Ankleiden & Haarstyling",
        "Cut & Color": "Schnitt & Farbe",
        "Head Spa": "Head Spa",
        "Nail Salon": "Nagelstudio",
        "Eyelash Extensions": "Wimpernverlängerung",
        "Okonomiyaki & Monjayaki": "Okonomiyaki & Monjayaki",
        "Soba & Udon": "Soba & Udon",
        "Tempura & Tonkatsu": "Tempura & Tonkatsu",
        "Indian Cuisine": "Indische Küche",
        "Chinese Cuisine": "Chinesische Küche",
        "Yakiniku & Horumon": "Yakiniku & Horumon",
        "Korean Cuisine": "Koreanische Küche",
        "Ramen": "Ramen",
        "Italian Cuisine": "Italienische Küche",
        "Sushi & Seafood": "Sushi & Meeresfrüchte",
        "100-Yen Shop": "100-Yen-Shop",
        "Outlet": "Outlet",
        "Household Goods": "Haushaltswaren",
        "General Discount": "Allgemeiner Discount",
        "Duty-Free Store": "Duty-free-Shop",
        "Anma & Shiatsu": "Anma & Shiatsu",
        "Reflexology (Foot Massage)": "Reflexzonenmassage (Fußmassage)",
        "Quick Massage": "Schnellmassage",
        "Dry Head Spa": "Trockenes Head Spa",
        "Thai Massage": "Thai-Massage",
        "Seitai & Chiropractic": "Seitai & Chiropraktik",
        "Oversized Luggage": "Übergroßes Gepäck",
        "Staffed Luggage Counter": "Betreuter Gepäckschalter",
        "Same-Day Hotel Delivery": "Hotellieferung am selben Tag",
        "Coin Lockers": "Münzschließfächer",
        "Airport Delivery": "Lieferung zum Flughafen",
        "Fitness Gym": "Fitnessstudio",
        "Bouldering": "Bouldern",
        "24-Hour Gym": "24-Stunden-Studio",
        "Yoga & Pilates": "Yoga & Pilates",
        "Pool & Swimming": "Pool & Schwimmen",
        "Golf Range": "Golf-Übungsplatz",
        "Large Bookstore": "Große Buchhandlung",
        "Art & Photography Books": "Kunst- & Fotobücher",
        "Foreign & Multilingual Books": "Fremdsprachige & mehrsprachige Bücher",
        "Manga & Comics": "Manga & Comics",
        "Antiquarian Books": "Antiquariat",
        "Supplements & Health Foods": "Nahrungsergänzung & Gesundheitskost",
        "Medicine & Remedies": "Arzneimittel & Hausmittel",
        "Cosmetics & Skincare": "Kosmetik & Hautpflege",
        "Hair & Body Care": "Haar- & Körperpflege",
        "Baby Products": "Babyartikel",
        "Gyudon (Beef Bowl)": "Gyudon (Rindfleischbowl)",
        "Curry": "Curry",
        "Fried Chicken": "Frittiertes Hähnchen",
        "Hamburgers": "Hamburger",
        "Sandwiches & Bakery": "Sandwiches & Bäckerei",
        "Standing Soba": "Steh-Soba",
        "Super Sento Bathhouse": "Super-Sento-Badehaus",
        "Natural Hot Spring": "Natürliche heiße Quelle",
        "Sauna": "Sauna",
        "Private Bath": "Privatbad",
        "Esthetic Spa": "Kosmetik-Spa",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (Steinsauna)",
        "Game Consoles & Software": "Spielkonsolen & Software",
        "Audio & Earphones": "Audio & Kopfhörer",
        "PC & Phone Accessories": "PC- & Handyzubehör",
        "Beauty Appliances": "Beauty-Geräte",
        "Cameras & Lenses": "Kameras & Objektive",
        "Kitchen Appliances": "Küchengeräte",
        "Multiplex Cinema": "Multiplex-Kino",
        "Anime Screenings": "Anime-Vorführungen",
        "Art-House Cinema": "Programmkino",
        "IMAX & 4DX": "IMAX & 4DX",
    },
    "it": {
        "Standing Bar": "Bar in piedi",
        "Whisky & Cocktail Bar": "Bar whisky e cocktail",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Birra artigianale e beer bar",
        "Wine Bar": "Wine bar",
        "Sake Bar": "Sake bar",
        "Sports Bar": "Sports bar",
        "Free-Time & Late-Night Pack": "Pacchetto libero e notturno",
        "Solo Karaoke": "Karaoke solo",
        "Collab & Anime Room": "Sala collab e anime",
        "Standard Karaoke Box": "Karaoke standard",
        "Party Room": "Sala feste",
        "Tickets & Services": "Biglietti e servizi",
        "Sweets & Ice Cream": "Dolci e gelati",
        "Drinks & Alcohol": "Bevande e alcolici",
        "Daily Goods & Sundries": "Articoli di uso quotidiano",
        "Bento & Onigiri": "Bento e onigiri",
        "Used & Retro Games": "Giochi usati e retrò",
        "CDs & Records": "CD e vinili",
        "Trading Cards": "Carte collezionabili",
        "Musical Instruments": "Strumenti musicali",
        "Figures & Hobby": "Figure e hobby",
        "Anime & Character Goods": "Articoli anime e personaggi",
        "Compact Car": "Auto compatta",
        "Luxury & Sports Car": "Auto di lusso e sportiva",
        "Minivan (Large Group)": "Minivan (gruppo numeroso)",
        "Car Sharing": "Car sharing",
        "Electric Vehicle": "Veicolo elettrico",
        "Standard Car": "Auto standard",
        "Vintage & Secondhand": "Vintage e usato",
        "Kimono & Traditional Wear": "Kimono e abiti tradizionali",
        "Fast Fashion": "Fast fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Scarpe e sneaker",
        "Sportswear": "Abbigliamento sportivo",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Torte e pasticceria",
        "Crepes & Pancakes": "Crepe e pancake",
        "Taiyaki & Dorayaki": "Taiyaki e dorayaki",
        "Soft Serve & Ice Cream": "Soft serve e gelati",
        "Chocolate Specialist": "Cioccolateria",
        "Wagashi (Japanese Sweets)": "Wagashi (dolci giapponesi)",
        "Bubble Tea & Drink Stand": "Bubble tea e chiosco di bevande",
        "Theme Cafe (Anime & Animals)": "Caffè a tema (anime e animali)",
        "Chain Cafe": "Caffè di catena",
        "House-Roasted Coffee": "Caffè tostato in casa",
        "Retro Kissaten": "Kissaten retrò",
        "Kimono Dressing & Hair Styling": "Vestizione kimono e acconciatura",
        "Cut & Color": "Taglio e colore",
        "Head Spa": "Head spa",
        "Nail Salon": "Nail salon",
        "Eyelash Extensions": "Extension ciglia",
        "Okonomiyaki & Monjayaki": "Okonomiyaki e monjayaki",
        "Soba & Udon": "Soba e udon",
        "Tempura & Tonkatsu": "Tempura e tonkatsu",
        "Indian Cuisine": "Cucina indiana",
        "Chinese Cuisine": "Cucina cinese",
        "Yakiniku & Horumon": "Yakiniku e horumon",
        "Korean Cuisine": "Cucina coreana",
        "Ramen": "Ramen",
        "Italian Cuisine": "Cucina italiana",
        "Sushi & Seafood": "Sushi e frutti di mare",
        "100-Yen Shop": "Negozio da 100 yen",
        "Outlet": "Outlet",
        "Household Goods": "Casalinghi",
        "General Discount": "Discount generale",
        "Duty-Free Store": "Negozio duty-free",
        "Anma & Shiatsu": "Anma e shiatsu",
        "Reflexology (Foot Massage)": "Riflessologia (massaggio plantare)",
        "Quick Massage": "Massaggio rapido",
        "Dry Head Spa": "Head spa a secco",
        "Thai Massage": "Massaggio thailandese",
        "Seitai & Chiropractic": "Seitai e chiropratica",
        "Oversized Luggage": "Bagagli fuori misura",
        "Staffed Luggage Counter": "Deposito bagagli con personale",
        "Same-Day Hotel Delivery": "Consegna in hotel in giornata",
        "Coin Lockers": "Armadietti a gettone",
        "Airport Delivery": "Consegna in aeroporto",
        "Fitness Gym": "Palestra fitness",
        "Bouldering": "Bouldering",
        "24-Hour Gym": "Palestra 24 ore",
        "Yoga & Pilates": "Yoga e pilates",
        "Pool & Swimming": "Piscina e nuoto",
        "Golf Range": "Campo pratica golf",
        "Large Bookstore": "Grande libreria",
        "Art & Photography Books": "Libri d'arte e fotografia",
        "Foreign & Multilingual Books": "Libri stranieri e multilingue",
        "Manga & Comics": "Manga e fumetti",
        "Antiquarian Books": "Libreria antiquaria",
        "Supplements & Health Foods": "Integratori e alimenti salutari",
        "Medicine & Remedies": "Farmaci e rimedi",
        "Cosmetics & Skincare": "Cosmetici e skincare",
        "Hair & Body Care": "Cura capelli e corpo",
        "Baby Products": "Prodotti per neonati",
        "Gyudon (Beef Bowl)": "Gyudon (ciotola di manzo)",
        "Curry": "Curry",
        "Fried Chicken": "Pollo fritto",
        "Hamburgers": "Hamburger",
        "Sandwiches & Bakery": "Panini e panetteria",
        "Standing Soba": "Soba in piedi",
        "Super Sento Bathhouse": "Bagni super sento",
        "Natural Hot Spring": "Sorgente termale naturale",
        "Sauna": "Sauna",
        "Private Bath": "Bagno privato",
        "Esthetic Spa": "Spa estetica",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (sauna di pietra)",
        "Game Consoles & Software": "Console e software",
        "Audio & Earphones": "Audio e auricolari",
        "PC & Phone Accessories": "Accessori PC e telefono",
        "Beauty Appliances": "Elettrodomestici di bellezza",
        "Cameras & Lenses": "Fotocamere e obiettivi",
        "Kitchen Appliances": "Elettrodomestici da cucina",
        "Multiplex Cinema": "Cinema multiplex",
        "Anime Screenings": "Proiezioni anime",
        "Art-House Cinema": "Cinema d'essai",
        "IMAX & 4DX": "IMAX e 4DX",
    },
    "nl": {
        "Standing Bar": "Staande bar",
        "Whisky & Cocktail Bar": "Whisky- & cocktailbar",
        "Izakaya": "Izakaya",
        "Craft Beer & Beer Bar": "Craftbier & bierbar",
        "Wine Bar": "Wijnbar",
        "Sake Bar": "Sakebar",
        "Sports Bar": "Sportsbar",
        "Free-Time & Late-Night Pack": "Vrije tijd- & nachtpakket",
        "Solo Karaoke": "Solo-karaoke",
        "Collab & Anime Room": "Collab- & animekamer",
        "Standard Karaoke Box": "Standaard karaokebox",
        "Party Room": "Feestruimte",
        "Tickets & Services": "Tickets & diensten",
        "Sweets & Ice Cream": "Zoetigheid & ijs",
        "Drinks & Alcohol": "Dranken & alcohol",
        "Daily Goods & Sundries": "Dagelijkse artikelen",
        "Bento & Onigiri": "Bento & onigiri",
        "Used & Retro Games": "Tweedehands & retrogames",
        "CDs & Records": "Cd's & platen",
        "Trading Cards": "Verzamelkaarten",
        "Musical Instruments": "Muziekinstrumenten",
        "Figures & Hobby": "Figuren & hobby",
        "Anime & Character Goods": "Anime- & karakterartikelen",
        "Compact Car": "Compacte auto",
        "Luxury & Sports Car": "Luxe- & sportwagen",
        "Minivan (Large Group)": "Minibus (grote groep)",
        "Car Sharing": "Autodelen",
        "Electric Vehicle": "Elektrisch voertuig",
        "Standard Car": "Standaardauto",
        "Vintage & Secondhand": "Vintage & tweedehands",
        "Kimono & Traditional Wear": "Kimono & traditionele kleding",
        "Fast Fashion": "Fast fashion",
        "Streetwear": "Streetwear",
        "Shoes & Sneakers": "Schoenen & sneakers",
        "Sportswear": "Sportkleding",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Taart & gebak",
        "Crepes & Pancakes": "Crêpes & pannenkoeken",
        "Taiyaki & Dorayaki": "Taiyaki & dorayaki",
        "Soft Serve & Ice Cream": "Softijs & ijs",
        "Chocolate Specialist": "Chocolatier",
        "Wagashi (Japanese Sweets)": "Wagashi (Japans snoep)",
        "Bubble Tea & Drink Stand": "Bubbelthee & drankstand",
        "Theme Cafe (Anime & Animals)": "Themacafé (anime & dieren)",
        "Chain Cafe": "Ketencafé",
        "House-Roasted Coffee": "Zelf gebrande koffie",
        "Retro Kissaten": "Retro-kissaten",
        "Kimono Dressing & Hair Styling": "Kimono aankleden & haarstyling",
        "Cut & Color": "Knippen & kleuren",
        "Head Spa": "Head spa",
        "Nail Salon": "Nagelsalon",
        "Eyelash Extensions": "Wimperextensions",
        "Okonomiyaki & Monjayaki": "Okonomiyaki & monjayaki",
        "Soba & Udon": "Soba & udon",
        "Tempura & Tonkatsu": "Tempura & tonkatsu",
        "Indian Cuisine": "Indiase keuken",
        "Chinese Cuisine": "Chinese keuken",
        "Yakiniku & Horumon": "Yakiniku & horumon",
        "Korean Cuisine": "Koreaanse keuken",
        "Ramen": "Ramen",
        "Italian Cuisine": "Italiaanse keuken",
        "Sushi & Seafood": "Sushi & zeevruchten",
        "100-Yen Shop": "100-yenwinkel",
        "Outlet": "Outlet",
        "Household Goods": "Huishoudelijke artikelen",
        "General Discount": "Algemene discount",
        "Duty-Free Store": "Belastingvrije winkel",
        "Anma & Shiatsu": "Anma & shiatsu",
        "Reflexology (Foot Massage)": "Reflexologie (voetmassage)",
        "Quick Massage": "Snelle massage",
        "Dry Head Spa": "Droge head spa",
        "Thai Massage": "Thaise massage",
        "Seitai & Chiropractic": "Seitai & chiropractie",
        "Oversized Luggage": "Extra grote bagage",
        "Staffed Luggage Counter": "Bemande bagagebalie",
        "Same-Day Hotel Delivery": "Bezorging bij hotel dezelfde dag",
        "Coin Lockers": "Muntkluisjes",
        "Airport Delivery": "Bezorging naar luchthaven",
        "Fitness Gym": "Fitnessgym",
        "Bouldering": "Boulderen",
        "24-Hour Gym": "24-uursgym",
        "Yoga & Pilates": "Yoga & pilates",
        "Pool & Swimming": "Zwembad & zwemmen",
        "Golf Range": "Golfoefenbaan",
        "Large Bookstore": "Grote boekhandel",
        "Art & Photography Books": "Kunst- & fotoboeken",
        "Foreign & Multilingual Books": "Buitenlandse & meertalige boeken",
        "Manga & Comics": "Manga & strips",
        "Antiquarian Books": "Antiquariaat",
        "Supplements & Health Foods": "Supplementen & gezondheidsvoeding",
        "Medicine & Remedies": "Medicijnen & huismiddelen",
        "Cosmetics & Skincare": "Cosmetica & huidverzorging",
        "Hair & Body Care": "Haar- & lichaamsverzorging",
        "Baby Products": "Babyproducten",
        "Gyudon (Beef Bowl)": "Gyudon (rundvleesbowl)",
        "Curry": "Curry",
        "Fried Chicken": "Gebakken kip",
        "Hamburgers": "Hamburgers",
        "Sandwiches & Bakery": "Sandwiches & bakkerij",
        "Standing Soba": "Staande soba",
        "Super Sento Bathhouse": "Super-sento badhuis",
        "Natural Hot Spring": "Natuurlijke warmwaterbron",
        "Sauna": "Sauna",
        "Private Bath": "Privébad",
        "Esthetic Spa": "Schoonheidsspa",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (steensauna)",
        "Game Consoles & Software": "Gameconsoles & software",
        "Audio & Earphones": "Audio & oordopjes",
        "PC & Phone Accessories": "Pc- & telefoonaccessoires",
        "Beauty Appliances": "Beautyapparaten",
        "Cameras & Lenses": "Camera's & lenzen",
        "Kitchen Appliances": "Keukenapparaten",
        "Multiplex Cinema": "Multiplexbioscoop",
        "Anime Screenings": "Anime-vertoningen",
        "Art-House Cinema": "Filmhuis",
        "IMAX & 4DX": "IMAX & 4DX",
    },
    "he": {
        "Standing Bar": "בר עמידה",
        "Whisky & Cocktail Bar": "בר וויסקי וקוקטיילים",
        "Izakaya": "איזקאיה",
        "Craft Beer & Beer Bar": "בירה מלאכה ובר בירה",
        "Wine Bar": "בר יין",
        "Sake Bar": "בר סאקה",
        "Sports Bar": "בר ספורט",
        "Free-Time & Late-Night Pack": "חבילת זמן חופשי ולילה",
        "Solo Karaoke": "קריוקי לבד",
        "Collab & Anime Room": "חדר קולאב ואנימה",
        "Standard Karaoke Box": "תא קריוקי רגיל",
        "Party Room": "חדר מסיבות",
        "Tickets & Services": "כרטיסים ושירותים",
        "Sweets & Ice Cream": "מתוקים וגלידה",
        "Drinks & Alcohol": "משקאות ואלכוהול",
        "Daily Goods & Sundries": "מוצרי יומיום",
        "Bento & Onigiri": "בנטו ואוניגירי",
        "Used & Retro Games": "משחקים משומשים ורטרו",
        "CDs & Records": "תקליטורים ותקליטים",
        "Trading Cards": "קלפי אספנות",
        "Musical Instruments": "כלי נגינה",
        "Figures & Hobby": "פיגרים ותחביב",
        "Anime & Character Goods": "מוצרי אנימה ודמויות",
        "Compact Car": "רכב קומפקטי",
        "Luxury & Sports Car": "רכב יוקרה וספורט",
        "Minivan (Large Group)": "מיניוואן (קבוצה גדולה)",
        "Car Sharing": "שיתוף רכב",
        "Electric Vehicle": "רכב חשמלי",
        "Standard Car": "רכב רגיל",
        "Vintage & Secondhand": "וינטג' ויד שנייה",
        "Kimono & Traditional Wear": "קימונו ולבוש מסורתי",
        "Fast Fashion": "אופנה מהירה",
        "Streetwear": "אופנת רחוב",
        "Shoes & Sneakers": "נעליים וסניקרס",
        "Sportswear": "ביגוד ספורט",
        "Select Shop": "חנות סלקט",
        "Cakes & Pastries": "עוגות ומאפים",
        "Crepes & Pancakes": "קרפים ופנקייקים",
        "Taiyaki & Dorayaki": "טאיאקי ודוראיאקי",
        "Soft Serve & Ice Cream": "גלידה רכה וגלידה",
        "Chocolate Specialist": "חנות שוקולד",
        "Wagashi (Japanese Sweets)": "וגאשי (מתוקים יפניים)",
        "Bubble Tea & Drink Stand": "באבל טי ודוכן משקאות",
        "Theme Cafe (Anime & Animals)": "קפה נושא (אנימה וחיות)",
        "Chain Cafe": "קפה רשת",
        "House-Roasted Coffee": "קפה קלוי במקום",
        "Retro Kissaten": "קיסאטן רטרו",
        "Kimono Dressing & Hair Styling": "הלבשת קימונו ועיצוב שיער",
        "Cut & Color": "תספורת וצבע",
        "Head Spa": "ספא ראש",
        "Nail Salon": "מכון ציפורניים",
        "Eyelash Extensions": "הארכת ריסים",
        "Okonomiyaki & Monjayaki": "אוקונומיאקי ומונג'איאקי",
        "Soba & Udon": "סובה ואודון",
        "Tempura & Tonkatsu": "טמפורה וטונקאטסו",
        "Indian Cuisine": "מטבח הודי",
        "Chinese Cuisine": "מטבח סיני",
        "Yakiniku & Horumon": "יאקיניקו והורומון",
        "Korean Cuisine": "מטבח קוריאני",
        "Ramen": "ראמן",
        "Italian Cuisine": "מטבח איטלקי",
        "Sushi & Seafood": "סושי ופירות ים",
        "100-Yen Shop": "חנות 100 ין",
        "Outlet": "אאוטלט",
        "Household Goods": "מוצרים לבית",
        "General Discount": "חנות זול כללית",
        "Duty-Free Store": "חנות פטורה ממכס",
        "Anma & Shiatsu": "אנמה ושיאצו",
        "Reflexology (Foot Massage)": "רפלקסולוגיה (עיסוי כפות רגליים)",
        "Quick Massage": "עיסוי מהיר",
        "Dry Head Spa": "ספא ראש יבש",
        "Thai Massage": "עיסוי תאילנדי",
        "Seitai & Chiropractic": "סייטאי וכירופרקטיקה",
        "Oversized Luggage": "מטען גדול במיוחד",
        "Staffed Luggage Counter": "דלפק שמירת מטען מאויש",
        "Same-Day Hotel Delivery": "משלוח למלון באותו יום",
        "Coin Lockers": "תאי אחסון במטבע",
        "Airport Delivery": "משלוח לשדה התעופה",
        "Fitness Gym": "חדר כושר",
        "Bouldering": "טיפוס בולדרינג",
        "24-Hour Gym": "חדר כושר 24 שעות",
        "Yoga & Pilates": "יוגה ופילאטיס",
        "Pool & Swimming": "בריכה ושחייה",
        "Golf Range": "מגרש אימון גולף",
        "Large Bookstore": "חנות ספרים גדולה",
        "Art & Photography Books": "ספרי אמנות וצילום",
        "Foreign & Multilingual Books": "ספרים לועזיים ורב-לשוניים",
        "Manga & Comics": "מנגה וקומיקס",
        "Antiquarian Books": "חנות ספרים ישנים",
        "Supplements & Health Foods": "תוספי תזונה ומזון בריאות",
        "Medicine & Remedies": "תרופות ותרופות בית",
        "Cosmetics & Skincare": "קוסמטיקה וטיפוח עור",
        "Hair & Body Care": "טיפוח שיער וגוף",
        "Baby Products": "מוצרי תינוקות",
        "Gyudon (Beef Bowl)": "גיודון (קערת בקר)",
        "Curry": "קארי",
        "Fried Chicken": "עוף מטוגן",
        "Hamburgers": "המבורגרים",
        "Sandwiches & Bakery": "כריכים ומאפייה",
        "Standing Soba": "סובה בעמידה",
        "Super Sento Bathhouse": "בית מרחץ סופר-סנטו",
        "Natural Hot Spring": "מעיין חם טבעי",
        "Sauna": "סאונה",
        "Private Bath": "אמבט פרטי",
        "Esthetic Spa": "ספא אסתטי",
        "Ganbanyoku (Stone Sauna)": "גנבניוקו (סאונת אבן)",
        "Game Consoles & Software": "קונסולות ותוכנה",
        "Audio & Earphones": "אודיו ואוזניות",
        "PC & Phone Accessories": "אביזרי מחשב וטלפון",
        "Beauty Appliances": "מכשירי יופי",
        "Cameras & Lenses": "מצלמות ועדשות",
        "Kitchen Appliances": "מכשירי מטבח",
        "Multiplex Cinema": "קולנוע מולטיפלקס",
        "Anime Screenings": "הקרנות אנימה",
        "Art-House Cinema": "קולנוע אמנותי",
        "IMAX & 4DX": "IMAX ו-4DX",
    },
    "tr": {
        "Standing Bar": "Ayakta bar",
        "Whisky & Cocktail Bar": "Viski & kokteyl barı",
        "Izakaya": "İzakaya",
        "Craft Beer & Beer Bar": "Craft bira & bira barı",
        "Wine Bar": "Şarap barı",
        "Sake Bar": "Sake barı",
        "Sports Bar": "Spor barı",
        "Free-Time & Late-Night Pack": "Serbest zaman & gece paketi",
        "Solo Karaoke": "Tek kişilik karaoke",
        "Collab & Anime Room": "Kolaborasyon & anime odası",
        "Standard Karaoke Box": "Standart karaoke odası",
        "Party Room": "Parti odası",
        "Tickets & Services": "Bilet & hizmetler",
        "Sweets & Ice Cream": "Tatlı & dondurma",
        "Drinks & Alcohol": "İçecek & alkol",
        "Daily Goods & Sundries": "Günlük eşyalar",
        "Bento & Onigiri": "Bento & onigiri",
        "Used & Retro Games": "İkinci el & retro oyunlar",
        "CDs & Records": "CD & plak",
        "Trading Cards": "Koleksiyon kartları",
        "Musical Instruments": "Müzik aletleri",
        "Figures & Hobby": "Figür & hobi",
        "Anime & Character Goods": "Anime & karakter ürünleri",
        "Compact Car": "Kompakt araç",
        "Luxury & Sports Car": "Lüks & spor araç",
        "Minivan (Large Group)": "Minivan (kalabalık grup)",
        "Car Sharing": "Araç paylaşımı",
        "Electric Vehicle": "Elektrikli araç",
        "Standard Car": "Standart araç",
        "Vintage & Secondhand": "Vintage & ikinci el",
        "Kimono & Traditional Wear": "Kimono & geleneksel giysi",
        "Fast Fashion": "Hızlı moda",
        "Streetwear": "Sokak giyimi",
        "Shoes & Sneakers": "Ayakkabı & spor ayakkabı",
        "Sportswear": "Spor giyim",
        "Select Shop": "Select shop",
        "Cakes & Pastries": "Pasta & tatlı",
        "Crepes & Pancakes": "Krep & pankek",
        "Taiyaki & Dorayaki": "Taiyaki & dorayaki",
        "Soft Serve & Ice Cream": "Soft dondurma & dondurma",
        "Chocolate Specialist": "Çikolata mağazası",
        "Wagashi (Japanese Sweets)": "Wagashi (Japon tatlıları)",
        "Bubble Tea & Drink Stand": "Bubble tea & içecek standı",
        "Theme Cafe (Anime & Animals)": "Temalı kafe (anime & hayvan)",
        "Chain Cafe": "Zincir kafe",
        "House-Roasted Coffee": "Yerinde kavrulmuş kahve",
        "Retro Kissaten": "Retro kissaten",
        "Kimono Dressing & Hair Styling": "Kimono giydirme & saç şekillendirme",
        "Cut & Color": "Kesim & renk",
        "Head Spa": "Saç spası",
        "Nail Salon": "Tırnak salonu",
        "Eyelash Extensions": "Kirpik uzatma",
        "Okonomiyaki & Monjayaki": "Okonomiyaki & monjayaki",
        "Soba & Udon": "Soba & udon",
        "Tempura & Tonkatsu": "Tempura & tonkatsu",
        "Indian Cuisine": "Hint mutfağı",
        "Chinese Cuisine": "Çin mutfağı",
        "Yakiniku & Horumon": "Yakiniku & horumon",
        "Korean Cuisine": "Kore mutfağı",
        "Ramen": "Ramen",
        "Italian Cuisine": "İtalyan mutfağı",
        "Sushi & Seafood": "Suşi & deniz ürünleri",
        "100-Yen Shop": "100 yenlik mağaza",
        "Outlet": "Outlet",
        "Household Goods": "Ev eşyaları",
        "General Discount": "Genel indirim",
        "Duty-Free Store": "Gümrüksüz mağaza",
        "Anma & Shiatsu": "Anma & shiatsu",
        "Reflexology (Foot Massage)": "Refleksoloji (ayak masajı)",
        "Quick Massage": "Hızlı masaj",
        "Dry Head Spa": "Kuru saç spası",
        "Thai Massage": "Tay masajı",
        "Seitai & Chiropractic": "Seitai & kayropraktik",
        "Oversized Luggage": "Büyük boy bagaj",
        "Staffed Luggage Counter": "Görevli bagaj bankosu",
        "Same-Day Hotel Delivery": "Aynı gün otele teslim",
        "Coin Lockers": "Jetonlu dolaplar",
        "Airport Delivery": "Havalimanına teslim",
        "Fitness Gym": "Fitness salonu",
        "Bouldering": "Bouldering",
        "24-Hour Gym": "24 saat spor salonu",
        "Yoga & Pilates": "Yoga & pilates",
        "Pool & Swimming": "Havuz & yüzme",
        "Golf Range": "Golf sahası",
        "Large Bookstore": "Büyük kitapçı",
        "Art & Photography Books": "Sanat & fotoğraf kitapları",
        "Foreign & Multilingual Books": "Yabancı & çok dilli kitaplar",
        "Manga & Comics": "Manga & çizgi roman",
        "Antiquarian Books": "Sahaf",
        "Supplements & Health Foods": "Takviye & sağlıklı gıda",
        "Medicine & Remedies": "İlaç & ev ilaçları",
        "Cosmetics & Skincare": "Kozmetik & cilt bakımı",
        "Hair & Body Care": "Saç & vücut bakımı",
        "Baby Products": "Bebek ürünleri",
        "Gyudon (Beef Bowl)": "Gyudon (dana kâsesi)",
        "Curry": "Köri",
        "Fried Chicken": "Kızarmış tavuk",
        "Hamburgers": "Hamburger",
        "Sandwiches & Bakery": "Sandviç & fırın",
        "Standing Soba": "Ayakta soba",
        "Super Sento Bathhouse": "Süper sento hamamı",
        "Natural Hot Spring": "Doğal kaplıca",
        "Sauna": "Sauna",
        "Private Bath": "Özel banyo",
        "Esthetic Spa": "Estetik spa",
        "Ganbanyoku (Stone Sauna)": "Ganbanyoku (taş sauna)",
        "Game Consoles & Software": "Oyun konsolları & yazılım",
        "Audio & Earphones": "Ses & kulaklık",
        "PC & Phone Accessories": "PC & telefon aksesuarları",
        "Beauty Appliances": "Güzellik cihazları",
        "Cameras & Lenses": "Kamera & lens",
        "Kitchen Appliances": "Mutfak cihazları",
        "Multiplex Cinema": "Multipleks sinema",
        "Anime Screenings": "Anime gösterimleri",
        "Art-House Cinema": "Sanat sineması",
        "IMAX & 4DX": "IMAX & 4DX",
    },
}
